import {
  PERMISSIONS,
} from "./permissions.js";

export const ROLE_PERMISSIONS = {
  OWNER: Object.values(PERMISSIONS),

  ADMIN: [
    PERMISSIONS.BUSINESS_READ,

    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,

    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,

    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_CANCEL,

    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,

    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.FINANCE_UPDATE,

    PERMISSIONS.DELIVERY_READ,
    PERMISSIONS.DELIVERY_CREATE,
    PERMISSIONS.DELIVERY_UPDATE,

    PERMISSIONS.COMPLAINT_READ,
    PERMISSIONS.COMPLAINT_CREATE,
    PERMISSIONS.COMPLAINT_UPDATE,
  ],

  STAFF: [
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,

    PERMISSIONS.INVENTORY_READ,

    PERMISSIONS.DELIVERY_READ,

    PERMISSIONS.COMPLAINT_READ,
    PERMISSIONS.COMPLAINT_CREATE,
    PERMISSIONS.COMPLAINT_UPDATE,
  ],
} as const;